module.exports = {
  mainScreen: {
    backgroundColor: '#000',
    marginTop: 0,
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
  },
  mainScreenDisplay: {
    backgroundColor: '#000',
    elevation: 10,
    borderRadius: 10,
    width: '95%',
    padding: 10,
  },
  mainScreenText: {
    fontSize: 80,
    textAlign: 'right',
    color: '#fff',
    fontWeight: '300',
  },
  mainScreenKeypad: {
    width: '100%',
    height: '55%',
    display: 'flex',
    backgroundColor: '#00000',
    marginTop: 10,
  },
  keypadRow: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-around',
    alignItems: 'center',
    padding: 5,
  },
  buttonMain: {
    width: 80,
    height: 80,
    backgroundColor: '#333333',
    // elevation: 10,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderRadius: 50,
  },
  buttonText: {
    color: '#fff',
    fontSize: 35,
  },
  buttonMainColor: {
    width: 80,
    height: 80,
    backgroundColor: '#ff9E0A',
    // elevation: 10,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderRadius: 50,
  },
  buttonMainTop: {
    width: 80,
    height: 80,
    backgroundColor: '#A5A5A5',
    // elevation: 10,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderRadius: 50,
  },
  buttonTextTop: {
    color: '#000',
    fontSize: 30,
  },
};
